# fly.toml app configuration file generated for restoremitm on 2023-08-01T18:56:29-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "restoremitm"
primary_region = "yyz"

[build]
  image = "mitm800/restore:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  StripeSettings__PublishableKey="pk_test_51NZcDuFCJZn1Idpg01VaFJ6qeQElxaosFsqn4udOSm7At6n76aTSvTbwVWZLjjBz3lIMPxyN4z5NarTiCN88h12X00Hs79w80R"
  Cloudinary__CloudName="dq8snv7mr"
  Cloudinary__ApiKey="567359282696356"


[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
